blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: /docs
    about: Check the documentation for answers
  - name: Discussions
    url: https://github.com/{{REPO_OWNER}}/{{REPO_NAME}}/discussions
    about: Ask questions and share ideas

